server:
  port: 8088
spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据池
    #    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动程序
    driver-class-name: org.mariadb.jdbc.Driver #数据库驱动程序
    url: jdbc:mariadb://42.192.232.52:3306/db_mgt?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
    username: root
    password: Jzxmadmin
    druid:
      initial-size: 5   # 初始化大小
      min-idle: 5       # 最小空闲连接个数
      max-active: 20    # 最大连接个数
      max-wait: 60000   # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000    # 配置间隔多久才进行一次监测，监测需要关闭的空闲连接，单位时毫秒
      min-evictable-idle-time-millis: 60000       # 配置一个连接在池中最小生存的时间
      validation-query: select 1                # 用来监测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true            # 不影响性能，并且保证安全性。如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false            # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false            # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      pool-prepared-statements: true   # 打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mariadb
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#  auto-dialect-class: druid

project-config:
  base-location: D:/default
  osgb-uri: /osgb
  kml-uri: /kml
  artificial-uri: /artificial
  panorama-uri: /panorama
  project-image-uri: /project-image
  # token存活时间3天
  time-to-alive: 259200000
  admin-login-router: 9sdAzx7f0sfX
